### ISSUE TITLE
Support PWM?

### ISSUE THREAD

**Issue by mralexgray** [fenichelar/Pin#1]
I do not see any way to `analogWrite()`.  Am I wrong?  Why the omission?

**Comment by fenichelar** [comment]
The idea with this library was to create a faster way to do `digitalWrite()` and other digital operations. The built in functions are very slow compared to this library. It is actually very simple to do `digitalWrite()` using direct port manipulation. Unfortunately, direct port manipulation is very ugly to read and not portable across different boards. So this library abstracts direct port manipulation with as little overhead as possible.

Improving the speed of `analogWrite()` is much more complicated and hardware limits the amount of improvement that could be done to be pretty small. I guess I could add an `analogWrite()` function that just calls the prebuilt `analogWrite()` function. This would allow you to use the object oriented approach to pins this library uses but would not give any speed improvement. In fact, it would be slightly slower, as it would add some overhead, not much though. This would increase the size of the library however, and I'm not sure how useful it would be.

That being said, I'll take a look at the size increase and I might potentially add it in the future.

**Comment by fenichelar** [comment]
Just realized you were talking about PWM not analog operations. This will be implemented in the future. It will be implemented very differently than `analogWrite()`. It will be more set frequency and duty cycle oriented instead of set voltage.

**Comment by mralexgray** [comment]
I implemented it myself (actually called it `setDuty`, lol), and would be happy to push the fork...  but it's really just an expanded call to `analogWrite`, as you mentioned.  It added very little to the compiled size, though , 1% if even. this is OK with me, as if you're gonna make your messages high-level, it's nice to keep them there...

Also, I added a pin description for the _attiny45_ to a file called _boards/others.h_ - if you're interested in expanding the repertoire of hardware that's supported..  lemme know. 🙉

**Comment by fenichelar** [comment]
Awesome. Push the fork and I'll take a look!

**Comment by fenichelar** [comment]
FYI, PWM can be done directly with port manipulation. This will likely be faster than `analogWrite()` because the built in functions are always pretty slow, but is much more complex. I was originally planning on doing this but there are only so many hours in a day so this library has kinda been on the back burner.  Feel free if you have time ;)

As far as additional hardware, just create a file for each board and you can have the compiler include the file based on the hardware selected. This is nice as it only includes the necessary data when compiled. You could support infinite boards without increasing the size of the library when compiled.

**Comment by fenichelar** [comment]
Completed - [Version 2.3.0](https://github.com/fenichelar/Pin/releases/tag/v2.3.0)
